name: Terraform Plan

on:
  pull_request:
    branches: [ main ]

jobs:
  terraform-plan:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tf.plan

    - name: Parse Terraform Plan
      uses: arjenschwarz/strata@bb9a43a7ef45cb9908929e9e1d433a071d6af009
      with:
        plan-file: tf.plan

  sample-danger-plan:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest

    - name: Parse Sample Danger Plan
      uses: arjenschwarz/strata@bb9a43a7ef45cb9908929e9e1d433a071d6af009
      with:
        plan-file: samples/danger-sample.json
        comment-header: "Danger Plan"

  sample-k8s-plan:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    - name: Parse k8s Plan
      uses: arjenschwarz/strata@bb9a43a7ef45cb9908929e9e1d433a071d6af009
      with:
        plan-file: samples/k8s-sample.json
        comment-header: "K8s Plan"


  sample-web-plan:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    - name: Parse Web Plan
      uses: arjenschwarz/strata@bb9a43a7ef45cb9908929e9e1d433a071d6af009
      with:
        plan-file: samples/web-sample.json
        comment-header: "Web Plan"


  sample-noop-plan:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    - name: Parse No-Op Plan
      uses: arjenschwarz/strata@bb9a43a7ef45cb9908929e9e1d433a071d6af009
      with:
        plan-file: samples/nochange-sample.json
        comment-header: "No-Op Plan"

  wildcards-plan:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    - name: Parse No-Op Plan
      uses: arjenschwarz/strata@bb9a43a7ef45cb9908929e9e1d433a071d6af009
      with:
        plan-file: samples/wildcards-sample.json
        comment-header: "Wildcards Plan"

  subdir-plan:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: latest
    - name: Subdir Terraform Init
      run: cd subdirtest && terraform init

    - name: Terraform Plan
      run: cd subdirtest && terraform plan -out=tf.plan

    - name: Parse Terraform Plan
      uses: arjenschwarz/strata@bb9a43a7ef45cb9908929e9e1d433a071d6af009
      with:
        plan-file: subdirtest/tf.plan